language: node_js
sudo: false

node_js:
  - "12"
  - "10"

matrix:
  fast_finish: true
  include:
    - node_js: "node"
      env: "NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly"
  allow_failures:
    - node_js: node
      env: "NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly"

cache:
  directories:
    - "node_modules"
